### ISSUE TITLE
Language request: Kurdish-Kurmanji

### ISSUE THREAD

**Issue by brandones** [tesseract-ocr/langdata#124]
It's the most popular dialect of Kurdish, written in a Latin alphabet with a few diacritics.

**Comment by Shreeshrii** [comment]
Please try the current kur_ara traineddata from tessdata_fast and
tessdata_best, it seems to be incorrectly labelled and might be for Kurdish
written in Latin script.

Provide the feedback after testing here, so that required changes can be
made.

**Comment by brandones** [comment]
The data in both kur and kur_ara is in Arabic script, neither is in a Latin script.

**Comment by Shreeshrii** [comment]
I am not referring to the langdata repo which has not been updated for
4.0.0.

There are traineddata files for kur_ara in tessdata_best and tessdata_fast.

You can use combine_tessdata to unpack the file and look at the unicharset
in it.

Use dawg2wordlist to convert the words dawg to the wordlist.

Of course, you could try to recognise any image with those traineddata
files and check output.

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tessdata_best/issues/23

**Comment by brandones** [comment]
Oh interesting! I will give that a try, thank you.

**Comment by brandones** [comment]
Yes, it's definitely trained on Kurmanji. It's doing a great job OCRing Kurmanji text. This is wonderful, thank you!

**Comment by Shreeshrii** [comment]
Thank you for your feedback.

We need to change the traineddata name so that it correctly reflects the language.

What would you suggest?

kur
kur_lat

Any other official language code for kurmanji.

**Comment by brandones** [comment]
Don’t use kur for anything.

Depends on if you’re more interested in the script or the dialect. There are a few Kurdish languages using each of the scripts, the Latin-based one and the Persian-based one. Historically Cyrillic and Armenian scripts have been used also. I’m guessing the language is itself important though.

The ISO 639-3 code for Kurmanji (aka Northern Kurdish) is kmr.

It wouldn’t be at all unreasonable to prefix it as kur_kmr, and refer to it as Kurdish Kurmanji. Or just list kmr as Kurdish Kurmanji.

Similarly, I’d recommend using ckb or kur_ckb for the one with the Arabic-based script, Sorani.

**Comment by Shreeshrii** [comment]
Thanks.

@jbreiden @theraysmith what is your recommendation? 

At a minimum kur_ara should be changed as it doesn't have Arabic in it.

**Comment by amitdo** [comment]
Shree, please send PRs.

**Comment by brandones** [comment]
In case it’s not clear, this choice impedes the development of Tesseract support for Zaza, Gorani/Horami, and Southern Kurdish, each of which will require quite different dictionaries.

**Comment by Shreeshrii** [comment]
@brandones  Yes, that will require different dictionaries. As of now I am not sure exactly which language dictionary is being used.

I am attaching a zip file with two traineddatas for Kurdish in Arabic script - Sorani. 

If you are familiar with the script, please review and provide feedback as to accuracy and also whether the word frequency list is appropriate. (or refer to someone who can provide that feedback). Thanks!

[kur_ara.traineddata.zip](https://github.com/tesseract-ocr/langdata/files/1944020/kur_ara.traineddata.zip)

**Comment by Shreeshrii** [comment]
https://en.wikipedia.org/wiki/Kurdish_languages

> ISO 639-3	kur – inclusive code
> Individual codes:
> ckb – Central Kurdish
> kmr – Northern Kurdish
> sdh – Southern Kurdish

ckb - Sorani (Arabic/Persian script).
kmr - Kurmanji (Latin script)

**Comment by Shreeshrii** [comment]
@zdenop This issue can be closed as `Kurdish-Kurmanji` is available at

https://github.com/tesseract-ocr/tessdata_best/blob/master/kmr.traineddata
https://github.com/tesseract-ocr/tessdata_fast/blob/master/kmr.traineddata

**Comment by YehyaChali** [comment]
I want to improve and work on Kurdish Kurmanji and Sorani for both Latin an Arabic scripts.
how can I do that?
what is needed to be done?
how can I submit it?

**Comment by Shreeshrii** [comment]
Kurdish-Kurmanji is available at

https://github.com/tesseract-ocr/tessdata_best/blob/master/kmr.traineddata
https://github.com/tesseract-ocr/tessdata_fast/blob/master/kmr.traineddata

https://github.com/tesseract-ocr/langdata_lstm/tree/master/kmr

You can test it to identify the improvements needed.

**Comment by Shreeshrii** [comment]
Sorani in Arabic script is not available in tessdata_best and tessdata_fast.

https://github.com/tesseract-ocr/langdata_lstm/tree/master/kur
has minimal language data available for it.

You will need to identify unicode fonts and training text for the same before running any training.

**Comment by YehyaChali** [comment]
thank you so much 
I just tested the kmr.traineddata

but for the sorani in Arabic script where can I train it?
what data is needed except for the text?

I mean do I need to do boxing some images?
can you show me an example of training in tessercat?
is there any documentation for training it?

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00

https://github.com/Shreeshrii/tess4training

**Comment by YehyaChali** [comment]
wonderful
thanks a lot
