### ISSUE TITLE
what is the use of Traintext ? Shouldnt it be images instead?

### ISSUE THREAD

**Issue by himansh123** [tesseract-ocr/langdata#139]
I looked into eng folder, it has a few files which I can use by merging it to my new files.
But what is the use of eng.traintext??? how can I use it?

**Comment by amitdo** [comment]
It can be used by text2image. Providing the images in the repo would bloat it.

For lstm training see:
https://github.com/tesseract-ocr/langdata_lstm

Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
