### ISSUE TITLE
Langdata for 3.02

### ISSUE THREAD

**Issue by garora** [tesseract-ocr/langdata#20]
I am looking for langdata (Tel, Kan, Guj). How can I get the langdata for 3.02, currently repository is saying langdata is for 3.04

CC: @jimregan

**Comment by amitdo** [comment]
Langdata for 3.02:
https://code.google.com/p/tesseract-ocr/downloads/list

**Comment by garora** [comment]
@amitdo - I downloaded the langdata files from that links a last month. These looks very heavy files also I am not getting good results with these files, for English language its showing meanconfidence is around 65%. This is really a painful for me.

**Comment by Maxiride** [comment]
How can I download a single language folder? Do I have to use git and do a clone request of the repo? Isn't an easier way?

**Comment by mYnDstrEAm** [comment]
You can use the Wayback Machine (https://archive.org/web/) for https://code.google.com/p/tesseract-ocr/ to get old versions of the language data.

@zdenop: the NuGet package also is 3.02 and one needs the language files for it - so pls either change the version of the NuGet package & the download or make the old language data available. **Until then this project seems to be broken.**

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Downloads

**Comment by zdenop** [comment]
@mYnDstrEAm:  NuGet package is not part of tesseract project => we do not manage it.

**Comment by theraysmith** [comment]
Not relevant to completing 4.00.

**Comment by amitdo** [comment]
If someone still uses 3.02 and needs the traineddata files, see
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-302
