### ISSUE TITLE
Use a different set of fonts for Persian

### ISSUE THREAD

**Issue by ebraminio** [tesseract-ocr/langdata#26]
(moved from https://github.com/tesseract-ocr/tesseract/issues/294)

First of all, thanks for adding support to tesseract finally. From quickly inspecting Persian related codes on tesseract I reached to https://github.com/tesseract-ocr/tesseract/blob/master/training/language-specific.sh#L520 which I can say speculatively is not a good set of fonts for training Persian printed text and can result in poor performance of OCR quality as most Persian fonts don't have the style these fonts have. On ["Font recognition using Variogram fractal dimension"](http://files.matlabsite.com/docs/papers/icee2012/2/icee2012-174.pdf), a good set of Persian fonts is introduced (second page, at the bottom) which as you can see there also, it is different from favorites Arabic language fonts (even the fact both are using Arabic script). So for training Persian OCR for tesseract I suggest adding or replacing current fonts with these free fonts, Nazli (i.e. Nazanin as indicated on that article) and Titr from Debian [fonts-farsiweb](https://packages.debian.org/search?keywords=fonts-farsiweb) package and also XB Zar and XB Yaghut from OFL licensed [xfonts](http://wiki.irmug.com/index.php/X_Series_2). Thank you.

**Comment by Shreeshrii** [comment]
@ebraminio  Please test with the latest BEST 4.0alpha traineddata and provide feedback at https://github.com/tesseract-ocr/tessdata/issues/70

**Comment by Shreeshrii** [comment]
https://fontlibrary.org/en/font/nazli

https://github.com/behnam/fonts-farsiweb/tree/master/ttf

http://wiki.irmug.com/index.php/X_Series_2

**Comment by ebraminio** [comment]
Great! Thanks for the work, I hadn't chance to test its quality but since you know about the fonts now I assume this is already done so do you like to close this as fixed? Thank you!

**Comment by Shreeshrii** [comment]
Yes. You can close this, since the issue is being tracked at  tesseract-ocr/tessdata#70.

> I assume this is already done 

I don't know about that since the training was done by Ray at Google.

**Comment by ebraminio** [comment]
Thanks!
