### ISSUE TITLE
kan.unicharambigs seems to be copy of eng.unicharambigs

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#28]
Reviving an old issue - see https://github.com/RaghavBhardwaj/tesseract-ocr/issues/801

> I am shocked to notice that kan.unicharambigs contains only English script 
> instead of kannada script . I had expected kan.unicharambigs will contain 
> kannada script only. 

Suggest building of https://github.com/tesseract-ocr/langdata/blob/master/kan/kan.unicharambigs based on https://storage.googleapis.com/google-code-attachments/tesseract-ocr/issue-801/comment-6/kan.DangAmbigs.txt and review by someone who knows kannada.

**Comment by theraysmith** [comment]
Unicharambigs isn't used by LSTM training or recognition.
