### ISSUE TITLE
Failed to initialise tesseract engine: .net 6.0 [Tesseract 4.1.1 + Tesseract.Data.English 4.0.0]

### ISSUE THREAD

**Issue by J35P1N** [tesseract-ocr/langdata#295]
Hi, I've recently been looking at Tesseract as a solution for providing OCR for driving licences however, I cannot seem to get the .Net implementations to play ball with what should be the matching learning data for the english language. My implmentation at the moment is super simple and i've created a new .Net 6.0 api project with the following controller code:

    [Route("api/[controller]")]
    public class OcrController : ControllerBase
    {
        public const string folderName = "images/";
        public const string trainedDataFolderName = "tessdata";

        [HttpPost]
        public string DoOCR([FromForm] OcrModel request)
        {

            string name = request.Image.FileName;
            var image = request.Image;

            if (image.Length > 0)
            {
                using (var fileStream = new FileStream(folderName + image.FileName, FileMode.Create))
                {
                    image.CopyTo(fileStream);
                }
            }

            string result = "";

            using (var engine = new TesseractEngine(@"./tessdata", request.DestinationLanguage, EngineMode.TesseractAndLstm))
            {
                using (var img = Pix.LoadFromFile(folderName + name))
                {
                    var page = engine.Process(img);
                    result = page.GetText();
                    Console.WriteLine(result);
                }
            }
            return String.IsNullOrWhiteSpace(result) ? "Ocr is finished. Return empty" : result;
        }

I've installed the following Nuget packages into the solution:

![image](https://user-images.githubusercontent.com/4697711/152590911-f894c876-0df4-4e9f-aef4-3c7bd9d0b143.png)

But when it comes to actually running the solution in Swagger or using Postman, as soon as it hits the TesseractEngine initialiser I get a "Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details." error. I've tried to use this link to diagnose the problem but to be honest it mostly suggests that there may be version differences between the language file and the tesseract version which in this case, both are using the 4.0.x versions so should be compatible.

I've checked the following:

- Ensured that the images folder exists
- Ensured that the eng.traineddata file is set to 'copy always' in properties
- Ensure that the x64 and x86 folders are also set to copy always 
- Tried different Engine modes but all of them seem to produce the same results

Any assistance with this issue would be greatly appreciated.

**Comment by FriedrichFroebel** [comment]
How is this related to this repository? This repository contains the data for training the models. Actual engine issues should be reported at the appropriate places - either at the base repository if it corresponds to a general issue or to the wrapper library you use (in your case the wrapper library seems to live at https://github.com/charlesw/tesseract).

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
