### ISSUE TITLE
Bigrams file not in sync with training text

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#30]
@theraysmith 

Ray, I am using a modified version of Sanskrit training text with Vedic accents, rupee sign etc. 

The font properties generation in the processing by tesstrain.sh script uses the ngrams file which seems to be based on the bigrams file

Is the bigrams file generated based on the training text? If so, is there a utility to create bigrams from training text.

Will use of a new training text which is not in sync with bigrams file cause errors during training?

**Comment by theraysmith** [comment]
These files aren't used by the LSTM training process.
