### ISSUE TITLE
Tatar language data

### ISSUE THREAD

**Issue by rsabirov** [tesseract-ocr/langdata#305]
I couldn't find data for Tatar language (tat) here, while I can see it in `tessdata`. 

Could you please add lang data for Tatar language here?

**Comment by stweil** [comment]
langdata is superseded by langdata_lstm. See https://github.com/tesseract-ocr/langdata_lstm/tree/main/tat.

**Comment by rsabirov** [comment]
@stweil thank you for promt reply. 

will ask my question there https://github.com/tesseract-ocr/langdata_lstm/issues/61
