### ISSUE TITLE
Add rupee sign to Devanagari.unicharset

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#31]
`₹ 0 60,69,203,215,84,106,1,24,97,129 Common 1260 4 1260 ₹	# ₹ [20b9 ]`

The glyph metrics need to be updated.

**Comment by theraysmith** [comment]
Rupee sign is already there, and the glyph metrics aren't used.

**Comment by Shreeshrii** [comment]
It is not there in the current
https://github.com/tesseract-ocr/langdata/blob/master/Devanagari.unicharset

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
