### ISSUE TITLE
Suggest 'deva' for Devanagari

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#41]
With LSTM training the dictionary dawg files have become optional. In light of this, I want to suggest an additional traineddata file for Devanagari script, which can cater to all main languages written in it.

The reason for suggesting this is, when I tested OCR on a Marathi text, a lot of words with rakaara were not recognised correctly. However, same page OCRed with Sanskrit recognised them correctly, but some others were incorrect.

So, in addition to the multiple traineddata for various languages written in Devaन

**Comment by amitdo** [comment]
Related papers:

[A Segmentation-Free Approach for Printed Devanagari Script Recognition](https://www.researchgate.net/publication/280777081_A_Segmentation-Free_Approach_for_Printed_Devanagari_Script_Recognition) (2015)
Tushar Karayil, Adnan Ul-Hasan, Thomas M. Breuel

[Can we build language-independent OCR using LSTM networks?](https://www.researchgate.net/publication/260341307_Can_we_build_language-independent_OCR_using_LSTM_networks)
 (2013)
Adnan Ul-Hasan, Thomas M. Breuel

More interesting papers about LSTM for OCR:
https://github.com/tmbdev/ocropy/wiki/Publications

**Comment by Shreeshrii** [comment]
List of unicode devanagari fonts that could be used for training, if not already being used

**Comment by amitdo** [comment]
Similary. it would be nice to have generic traineddata for multiple Latin script based langs, as described in the above paper.

Likewise, you could provide a generic Cyrillic traineddata.

**Comment by amitdo** [comment]
And maybe one based on the Arabic script.

**Comment by Shreeshrii** [comment]
Devanagari corpus

Marathi
http://www.cfilt.iitb.ac.in/hin_corp_unicode.tar
http://ltrc.iiit.ac.in/ltrc/internal/nlp/corpus/ftp/marathicorp.tgz

Hindi
http://www.cfilt.iitb.ac.in/hin_corp_unicode.tar
http://ltrc.iiit.ac.in/ltrc/internal/nlp/corpus/ftp/hindicorp.tgz
http://ocr.iiit.ac.in/Hindi100.html

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/langdata/issues/41#issuecomment-272718868
@stweil 
I think it's related to your message here:
https://groups.google.com/forum/#!topic/tesseract-dev/8H_4K3vPRJE

**Comment by stweil** [comment]
> Likewise, you could provide a generic Cyrillic traineddata.

I assume the same would be needed for Greek. Or would it be better to include Greek characters in the Latin training set? Several sciences (especially Physics and Mathematics) use single Greek characters in texts which are mostly written with Latin letters.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/langdata/issues/59#issuecomment-290235084

>@theraysmith commented 2 days ago

>I've also added an experiment to throw *all* the Latin languages together
into a single engine. (Actually a separate model for each of 36 scripts).
If that works it will solve the problem of reading Citroen in German and
picking up the e umlaut.
The downside is that this model has almost 400 characters in it, despite
carefully keeping out the long-tail graphics characters. Even if it does
work, it will be slower, but possibly not much slower than running 2
languages. It will have about 56 languages in it. I have some optimism that
this may work, ever since I discovered that the vie LSTM model gets the
phototest.tif image 100% correct.

**Comment by amitdo** [comment]
This request was implemted by Ray:


https://github.com/tesseract-ocr/tessdata/issues/62#issuecomment-319442674

**Comment by Shreeshrii** [comment]
Thanks!
