### ISSUE TITLE
Myanmar  Resources

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#46]
Ref: https://github.com/tesseract-ocr/tesseract/issues/654#issuecomment-274269267

Myanmar Unicode Fonts

http://www.myanmarlanguage.org/unicode/myanmar-fonts-which-follow-unicode-rules
http://www.mymfont.com/

mya - my - Myanmar - http://crubadan.org/languages/my

**Comment by Shreeshrii** [comment]
@theraysmith 

Please also see https://github.com/tesseract-ocr/langdata/issues/13

**Comment by herzcthu** [comment]
Myanmar wordlists
https://github.com/kanaung/wordlists

**Comment by Shreeshrii** [comment]
Closing this, so that all discussion is in one place - https://github.com/tesseract-ocr/langdata/issues/13
