### ISSUE TITLE
Tigrigna Resources

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#49]
Ref: https://github.com/tesseract-ocr/tesseract/issues/654#issuecomment-274269267

tir - ti - Tigrigna - http://crubadan.org/languages/ti

**Comment by zmeharen** [comment]
Hi Shreeshrii,

I have been working on improving Tesseract's ability to recognize Tigrinya (ti or tir) language from PDF and other image files. I have noticed a few errors and I have been working on training the software. I have been working on it for about a week. Thank you for posting the link it has helped me in finding the resources I need. If you need help with this language let me know. I might need some guidance or direction but I will do what I can to help. Thank You,

Z

**Comment by Shreeshrii** [comment]
Thanks.

Please share the errors that you have noticed, since @theraysmith is
retraining all the languages, and your feedback may help improve this
language's recognition.


- excuse the brevity, sent from mobile


On 24-Feb-2017 6:15 PM, "zmeharen" <notifications@github.com> wrote:

Hi Shreeshrii,

I have been working on improving Tesseract's ability to recognize Tigrinya
(ti or tir) language from PDF and other image files. I have noticed a few
errors and I have been working on training the software. I have been
working on it for about a week. Thank you for posting the link it has
helped me in finding the resources I need. If you need help with this
language let me know. I might need some guidance or direction but I will do
what I can to help. Thank You,

Z

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/langdata/issues/49#issuecomment-282282856>,
or mute the thread

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/issues/654#issuecomment-274574951

>@theraysmith commented 2 days ago
Update: after going back to the www to get fresh data, I believe that my corpus text is now good for:
chr
dzo
iku
snd
syr
tgk
tir
I have put a lot of time into cleaners/filters for languages that use 'virama' characters.
I am not convinced that they are perfect, but I will add the code to the github repo in due course, so experts/native speakers can offer suggestions/fixes to make them better.
