### ISSUE TITLE
Maldivian - Dhivehi - Thaana

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#52]
https://en.wikipedia.org/wiki/Maldivian_writing_systems

https://www.ethnologue.com/language/div

http://scriptsource.org/cms/scripts/page.php?item_id=script_detail&key=Thaa

http://scriptsource.org/cms/scripts/page.php?item_id=script_detail&key=Qa61

Ref: https://github.com/tesseract-ocr/tesseract/blob/master/training/language-specific.sh#L31

**Comment by Shreeshrii** [comment]
https://dhivehi.mv/fonts/

http://www.wazu.jp/gallery/Fonts_Thaana.html

http://www.fontspace.com/category/thaana

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/langdata/issues/59#issuecomment-290235084

> @theraysmith commented 2 days ago
After a *lot* of work, and a very long delay, the new training is almost
ready to go. Just waiting for rendering to finish...

>Fixes in this round:
Utilizes a new crawl of the www for ~60 languages that had the least
training data, and ~15 *new* languages that we didn't have before.
This provides *much* more training data, with  data, with better estimates of what is
in the character set and better wordlists.

**Comment by nashrafeeg** [comment]
> [#59 (comment)](https://github.com/tesseract-ocr/langdata/issues/59#issuecomment-290235084)
> 
> > @theraysmith commented 2 days ago
> > After a _lot_ of work, and a very long delay, the new training is almost
> > ready to go. Just waiting for rendering to finish...
> 
> > Fixes in this round:
> > Utilizes a new crawl of the www for ~60 languages that had the least
> > training data, and ~15 _new_ languages that we didn't have before.
> > This provides _much_ more training data, with  data, with better estimates of what is
> > in the character set and better wordlists.

hi @Shreeshrii is dhivehi now fully supported ?
