### ISSUE TITLE
French 'ï' is recognized as 'i'

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/langdata#53]
Originally reported by @jbarlow83 in the tesseract-dev forum.

>Umlaut on the letter in French ï seems to be read as a regular i, e.g. the word "ovoïde".

**Comment by amitdo** [comment]
In [fra.training_text](https://github.com/tesseract-ocr/langdata/raw/master/fra/fra.training_text) there are 4 occurrences of `ï` and 340 of `i`.

**Comment by jbarlow83** [comment]
![_francais-000](https://cloud.githubusercontent.com/assets/1825843/22834822/64ee3fd4-ef6b-11e6-8584-69930a0e857e.png)

Here is my test image. PNG is to preserve JPEG artifacts in case they were related.

```
$ sha1sum tessdata/fra.traineddata 
fd9b7f0c3cc7df2d6efba537f011e14287c239fc  tessdata/fra.traineddata
$ api/tesseract -l fra --tessdata-dir . --oem 1 _francais-000.png stdout

Portez ce vieux whisky au juge
blond qui fume sur son île
intérieure, à côté de l'alcôve
ovoide, où les bûches se     # <---- right here
consument dans l'âtre, ce qui
lui permet de penser à la
cænogénèse de l'être dont il
est question dans la cause
ambiguë entendue à Moÿ, dans
un capharnaüm qui, pense-t-il,
diminue çà et là la qualité de son
œuvre.
```

**Comment by theraysmith** [comment]
Is this fixed in the new best traineddata?

**Comment by amitdo** [comment]
@jbarlow83?

**Comment by jbarlow83** [comment]
@theraysmith @amitdo  Oui, c'est bon.

Using
```
833b76bd14ececd34d13c20471390037edcaa4d6  tessdata/fra.traineddata
```

**Comment by amitdo** [comment]
You can put the 'best' traineddata in a 'best' directory in your TESSDATA_PREFIX and use -l best/fra.
