### ISSUE TITLE
tessedit_load_sublangs chi_sim_vert

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#73]
chi_sim config file loads chi_sim_vert
but this does not exist in tessdata 
and
langdata only has some stub files in the directory.

Similarly for other CJK languages which have vertical versions.

**Comment by theraysmith** [comment]
They are in best.
You need to either move the best files to tessdata, or make tessdata-dir point to best.
The solution of using best/chi_sim as a language does not work for precisely this reason.
