### ISSUE TITLE
Add 3.05 branch

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/langdata#79]
@zdenop Please add a 3.05 branch, so that langdata changes for 3.0x and 4.0x can be updated separately.

**Comment by zdenop** [comment]
What kind of "3.05 updates" are planned for langdata?

**Comment by stweil** [comment]
See PR #77. It is needed for 3.05, too.

**Comment by Shreeshrii** [comment]
eg. Sanskrit Wordlist includes punctuation. It also has some characters that though part of Devanagari script, are not used in Sanskrit language.

**Comment by zdenop** [comment]
#77 was merged and AFAIK there no more problems like this. But nobody will regenerate binary part of trainneddata files.

**Comment by stweil** [comment]
#77 was merged in the master branch, but the same change is needed for 3.05, too.

I also fixed the binary part for the master branch (see https://github.com/tesseract-ocr/tessdata/pull/57), but cannot fix the binary part for 3.05 because there is no branch for that version.

**Comment by zdenop** [comment]
IMO updates/fixes will be in master. Do we really need to create new branch of langdata just for 3.05?
