### ISSUE TITLE
[Feature request] font list for LSTM

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/langdata#86]
@theraysmith, please add the names of the fonts you trained for each language/script to the langdata repo.

**Comment by roozgar** [comment]
maybe a repository for upload font is useful
yiu can add some famous fonts of each language to tesseract...

**Comment by Shreeshrii** [comment]
Duplicate https://github.com/tesseract-ocr/langdata/issues/98

**Comment by amitdo** [comment]
Duplicate #98 

It's vice versa... :-)

**Comment by Shreeshrii** [comment]
On Mon, Feb 26, 2018 at 7:50 PM, Amit D. <notifications@github.com> wrote:

> Duplicate #98 <https://github.com/tesseract-ocr/langdata/issues/98>
>
> It's vice versa... :-)
>
>
​Sorry about that.​

**Comment by amitdo** [comment]
Shree, It's OK! :-)

**Comment by stweil** [comment]
Now both issues are closed, but the initial request is still open. I suggest to re-open #86 and assign it to @theraysmith.

**Comment by amitdo** [comment]
>Now both issues are closed, 

Someone is confused...
> zdenop reopened this a day ago

:smile:

**Comment by amitdo** [comment]
Ray provided the font list for Hebrew in https://github.com/tesseract-ocr/langdata/issues/82#issuecomment-320100717
https://github.com/tesseract-ocr/langdata/files/1198659/hebrewfonts.txt

**Comment by Shreeshrii** [comment]
Another list of fonts, without language wise breakup can be seen in

https://github.com/tesseract-ocr/langdata/blob/master/font_properties

**Comment by Shreeshrii** [comment]
The training scripts, used by tesstrain.sh also have a list of fonts,
sorted by scripts/languages.

https://github.com/tesseract-ocr/tesseract/blob/master/training/language-specific.sh

However, both these links do not necessarily reflect the exact set of fonts
used for LSTM training.

**Comment by stweil** [comment]
Large parts of `language-specific.sh` are still from 3.05 – I see no new fonts for LSTM there. For `font_properties` the situation is similar. So both files might include fonts used for LSTM, but we can only guess.

**Comment by Shreeshrii** [comment]
@stweil You are correct. I just wanted to link all the available list of
fonts in one place. We will not know the fonts used by Ray for LSTM till he
provides new version of these.

**Comment by amitdo** [comment]
@jbreiden,

Do you have access to the font lists? 
If you do, any chance you can upload them to this repo?

**Comment by jbreiden** [comment]
https://github.com/tesseract-ocr/langdata_lstm/blob/master/font_properties

**Comment by jbreiden** [comment]
Maybe I'm missing something. I'll try to hunt down Ray and find out.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/langdata/issues/86#issuecomment-368961594tps://github.com/tesseract-ocr/langdata/issues/86#issuecomment-368961594

>Ray provided the font list for Hebrew in #82 (comment)
https://github.com/tesseract-ocr/langdata/files/1198659/hebrewfonts.txt

Try to find it in the Google (langdata?) repo if you still have access to it.

**Comment by jbreiden** [comment]
I talked to Ray, tracked them down, and uploaded to Github. Sorry for not having these earlier.

https://github.com/tesseract-ocr/langdata_lstm/blob/master/heb/okfonts.txt

**Comment by amitdo** [comment]
Thank you!
