### ISSUE TITLE
how to train text for multiple fonts?

### ISSUE THREAD

**Issue by aijianiula0601** [tesseract-ocr/langdata#92]
I want to train text for multiple fonts. Is that the only way to train times as flowing:

text2image --text=text_training.txt --outputbase=tb --font='Tahoma Bold' --fonts_dir=/Users/*/fonts
?
Have a way to train with multiple fonts once? 
Thanks！

**Comment by Shreeshrii** [comment]
Follow the following format for using multiple fonts:

   training/tesstrain.sh \
--fonts_dir /mnt/c/Windows/Fonts \
 --lang mar \
 --noextract_font_properties  --linedata_only \
 --exposures "0" \
 --langdata_dir ../langdata \
 --tessdata_dir ../tessdata \
 --fontlist \
  "Adobe Devanagari" \
  "Arial Unicode MS" \
  "Nakula" \
  "Sahadeva" \
  --output_dir ../tesstutorial/mar

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
@zdenop This issue can be closed.
