### ISSUE TITLE
what's the difference among chi_sim.traineddata  and these chi_sim.* files?

### ISSUE THREAD

**Issue by wamlvaw** [tesseract-ocr/langdata#93]
my tesseract-ocr is the 3.04 edition, however on the RPi, I ran the command of "sudo apt-get install tesseract-ocr-chi-sim". I tested a picture and it showed 
"Error opening data file /usr/local/share/tessdata/chi_sim.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'chi_sim'
Tesseract couldn't load any languages!
"
And I guessed whether the edition is 3.02. 
When I find these files, I'm lost in how to transfer them into chi_sim.traineddata. 
Could you please give me several suggestions? Thank you!

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/wiki/Data-Files

You may want to upgrade your tesseract-ocr installation. 
https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr

**Comment by Shreeshrii** [comment]
@zdenop This issue can be closed.
