### ISSUE TITLE
why eng.training_text just has 72 lines?

### ISSUE THREAD

**Issue by xiaomaxiao** [tesseract-ocr/langdata#94]
it's not enough for training lstm 4.0

**Comment by Shreeshrii** [comment]
Langdata has not been updated for 4.0

You can use current files for finetuning, not for training from scratch.

**Comment by xiaomaxiao** [comment]
@Shreeshrii  thanks .

**Comment by Layneww** [comment]
@Shreeshrii Hi! I'm trying to replicate the lstm model via tensorflow, but the problem is  regarding the language data. Is there any update on the langdata for 4.0, or can I generate the same training data myself based on the current information? Thanks!
