### ISSUE TITLE
List of fonts for training lang

### ISSUE THREAD

**Issue by masztal** [tesseract-ocr/langdata#98]
I want to reproduce the training exactly. Where can I obtain the list of fonts needed to train the language?

**Comment by stweil** [comment]
I'm afraid that it is currently not possible to reproduce the training. Not only the font list used for the different languages is missing, but also the texts used for the training.

Even with the font list it would be extremely difficult to get all fonts, as not all of them are freely available.

We have to wait until @theraysmith updates [langdata](https://github.com/tesseract-ocr/langdata). Maybe we'll know more then.

**Comment by amitdo** [comment]
#86

**Comment by masztal** [comment]
thanks for info
